### ISSUE TITLE
Can't discover 5.4.3p4

### ISSUE THREAD

**Issue by samizzo** [sttz/install-unity#11]
The script won't detect 5.4.3p4, and in fact won't find any patch releases for 5.4.3 at all. It does however show me 5.4.5p4 in the 5.4 series. I didn't quite understand the note in the readme about only discovering the latest 5 patch releases, so maybe this is correct behavior.

**Comment by samizzo** [comment]
Ahh, from looking at https://unity3d.com/unity/qa/patch-releases I see that there are five patches shown on the first page, so I guess that's what you're referring to!

**Comment by samizzo** [comment]
Actually even if I use the `--discover` option I can't get it to find it. This is the url for the Mac editor download: http://files.unity3d.com/download/4dfc8d4040f2/MacEditorInstaller/Unity-5.4.3p4.pkg but the ini file doesn't seem to exist.

**Comment by samizzo** [comment]
Ok sorry for all the messages. It looks like http://beta.unity3d.com/download/4dfc8d4040f2/MacEditorInstaller/Unity-5.4.3p4.pkg is the correct url, even though the other url is linked to from the patch download page!

**Comment by sttz** [comment]
Hey, sorry for the confusion! Unfortunately, Unity doesn't publish a comprehensive list of versions anywhere and I want to be restrained with scraping their website. Hence the limited number of patch releases that install-unity automatically discovers.

For me, the first link (files.unity3d.com/…) works as well. Did you get an error when you tried to add it?

Note that with the newest install-unity version, patch releases don't show up in the list of versions by default, so you need to call `install-unity --list patch` to show them.

**Comment by sttz** [comment]
btw, just committed 4ad7c9a2, which should make this much easier: In case you select a patch or beta version that is not in the cache and you enter the full version number, install-unity now tries to guess the release notes URL and scrapes it for the installer URL.

So, in case the patch release you want to install is not among the newest five, you can give install-unity the exact version (e.g. 5.4.3p4) and then it should find it automatically without having to use `--discover`.

**Comment by samizzo** [comment]
I don't remember now if I got an error message. I'll double check what happened. I just remember that there was no unity-xxx-osx.ini file at that url.

That new feature sounds really great though, thanks!
