### ISSUE TITLE
LibreSSL not supported

### ISSUE THREAD

**Issue by ohbibi-bhallion** [sttz/install-unity#14]
Hello,

Today while deploying unity on some new machine, install-unity.py was stuck because of my version of OpenSSL which was in fact LibreSSL.

I quick-fixed the script so it can accept LibreSSL.

    
    def main():

    [...]

    match = re.match('OpenSSL (\d+).(\d+).(\d+)(\w+)', ssl.OPENSSL_VERSION)
    
    if not match:
        match = re.match('LibreSSL (\d+).(\d+).(\d+)', ssl.OPENSSL_VERSION)
    if not match:
        print 'ERROR: Could not parse OpenSSL/LibreSSL version: %s' % ssl.OPENSSL_VERSION
        sys.exit(1)

    [...]

Everything worked just fine.

**Comment by sttz** [comment]
Thanks for the report!

Since the check is for the OpenSSL that ships with macOS, which isn't able to make connections to unity3d.com anymore, it would probably be better to just continue if the version cannot be matched.
