### ISSUE TITLE
ERROR: Your Python's OpenSSL library is outdated.

### ISSUE THREAD

**Issue by Geri-Borbas** [sttz/install-unity#15]
Hi,
Could you please help me fix this Travis CI instance at [`Unity.Test.eppz`](https://travis-ci.org/eppz/Unity.Test.eppz)?
I has just stopped working after I updated [`install-unity.py`](https://github.com/eppz/Unity.Test.eppz/tree/master/.scripts).
It says:

```
Install Unity Script 0.1.1
ERROR: Your Python's OpenSSL library is outdated (OpenSSL 0.9.8zh 14 Jan 2016).
At least OpenSSL version 1.0.1g is required.
You need to install a new version of Python 2 with an updated OpenSSL library.

Either download it from www.python.org or install it using a package manager like Homebrew.
```

Should I just install a specific Python version?
Or what is exactly I should install with Homebrew?
Could you please suggest me a change to this setup:

```
os: osx
language: generic
python:
  - 3.6
install:  
  - sudo python .scripts/install-unity.py --package Unity 2017.1.1f1
script:
  - .scripts/test $TRAVIS_BUILD_DIR eppz.TestResult.xml
```

**Comment by Geri-Borbas** [comment]
I tried to install using:

```
brew install openssl
brew link --force openssl
```

It says:
```
Error: openssl 1.0.2l is already installed
To upgrade to 1.0.2n, run `brew upgrade openssl`
```

It sounds good actually, but I get the same error from [`install-unity.py`](https://github.com/eppz/Unity.Test.eppz/tree/master/.scripts).

```
Install Unity Script 0.1.1
ERROR: Your Python's OpenSSL library is outdated (OpenSSL 0.9.8zh 14 Jan 2016).
At least OpenSSL version 1.0.1g is required.
You need to install a new version of Python 2 with an updated OpenSSL library.

Either download it from www.python.org or install it using a package manager like Homebrew.
```

Now I get that it is about "...**Python's** OpenSSL library...". Could you help me on how to update Python's OpenSSL library?

**Comment by Geri-Borbas** [comment]
Now I tried:

```
brew install python --with-brewed-openssl
```

Which says:

```
Warning: python 2.7.14 is already installed
```

**Isn't there a way to tell Python that OpenSSL is already there?**
I'm also keep trying to pick up the information at [Stackoverflow](https://stackoverflow.com/questions/47897823/update-pythons-openssl-library-to-1-0-1-on-travis-ci).

Or a way to tell [`install-unity.py`](https://github.com/eppz/Unity.Test.eppz/blob/master/.scripts/install-unity.py) to use "brewed" OpenSSL?

**Comment by Geri-Borbas** [comment]
As I figured out I have to add something to `CFLAGS` and `LDFLAGS `, that Python may (?) pick up.

So I tried:

```
before_install:
  - export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS"
  - export LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"
```

But still the same error. 😧

**Comment by Geri-Borbas** [comment]
I gave it a try with package manager:

```
pip2 install pyOpenSSL --upgrade
```

That is installed fine, but I still get the very same error.

I'd appreciate if **you could get back**, to give a pointer at least where should I go next.

**Comment by Geri-Borbas** [comment]
Can I somehow edit [`install-unity.py`](https://github.com/eppz/Unity.Test.eppz/blob/master/.scripts/install-unity.py) to pick up OpenSSL at `/usr/local/opt/openssl/include`?

**Comment by sttz** [comment]
It seems Homebrew changed how it installs Python 2 and no longer shadows/overrides the preinstalled version of Python. Homebrew now installs its own version as `python2`, so you should update your setup to use `python2` instead of `python`.

**Comment by Geri-Borbas** [comment]
Thanks, Travis CI basically responded somewhat the same:

> Thanks for writing in. That is... surprising... We would recommend to try out the most recent OSX image by specifying the following in your .travis.yml:
```
osx_image: xcode9.2
```
> If that would not work out, we would recommend looking into installing the latest version of Python2 through Brew (untested):
```
before_install:
  - brew update
  - brew install python
  - sudo python -m ensurepip
```

I'm testing, will get back with the results.

**Comment by Geri-Borbas** [comment]
Thanks, using **`python2`** solved my issue.

```
$ python2 -c 'import ssl; print ssl.OPENSSL_VERSION;'
OpenSSL 1.0.2m  2 Nov 2017
```
