### ISSUE TITLE
Feature request: Get path to Unity.app

### ISSUE THREAD

**Issue by rgov** [sttz/install-unity#18]
I'm planning to use `install-unity` in a Travis CI pipeline, and I think it's going to work great. Thank you for your time developing it.

It would be nice to have a feature that prints out the path to the Unity.app for a given installed version, like:

```
$ python2 install-unity.py --path 2018.2.0f2
/Applications/Unity 2018.2.0f2/Unity.app
```

Ideally, if there is only one Unity installed, it would be possible to omit the version number.

This would roughly parallel `brew --prefix python@2` or `xcrun --find xcodebuild` and make it easier to correctly invoke Unity in batch mode from inside CI scripts without hard-coding the install path.

This is also important because when I install multiple copies of Unity at once, `install-unity` puts them in different paths depending on what order they are installed in. As a result, if I'm trying to automate setup of a machine, I'll get different results depending on whether Unity was already installed. I need a way to reliably access the path of the version of Unity that my automation installed.

```
script:
  - "$(python2 install-unity.py --path)"/Contents/MacOS/Unity -quit -batchmode -projectPath . -executeMethod Foo.Bar
```

**Comment by sttz** [comment]
The [beta of the new version](https://github.com/sttz/install-unity/tree/next) has this feature:

    install-unity list --installed

You can filter the versions to list only some of them:

    install-unity list -i 2018.2

The versions are sorted from newest to oldest, so you can just use the first line to use the latest of all matching versions.

The new version can also run Unity for you, given a version or path to a project:

    install-unity run /my/project -- -batchmode -quit -buildOSX64Player /path/to/build

I won't be backporting this to the Python version but I'll accept a PR if someone wants to.
