### ISSUE TITLE
Running on a virtual machine fail

### ISSUE THREAD

**Issue by LymarV** [sttz/install-unity#22]
Hi!

Thanks for developing such great utility!
Though, I'm having troubles using it with a CI system (virtual macOS machine). I'm trying to run it on bitrise.io, but it does fail on a download start.
Here are some logs:
```
Selected 2018.3.11f1 (5063218e4ab8) for input 2018.3.11f
Selected packages:
- Unity (944.01 MB)
- iOS (1.04 GB)
Will download 1.96 GB and install 5.05 GB
                                                                                HASH Unity ║▏·····························║                                                  0 B of 944.01 MB @       0 B/s
HASH iOS   ║▏·····························║                                                  0 B of   1.04 GB @       0 B/s
The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -3.
```

I'm executing this command:
`sudo ./install-unity install 2018.3.11 -y -p Unity iOS`

Any ideas what's happening there or how to fix it?

Thanks a lot!

**Comment by sttz** [comment]
Please see #21 for a workaround and progress on the fix.
