### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by capyvara** [sttz/install-unity#24]
I've setup HomeBrew formula on my personal tap here: 
https://github.com/capyvara/homebrew-tap/blob/master/install-unity.rb

```
brew tap capyvara/tap
brew install install-unity
```

Maybe setting up a tap on your own users should be better to keep versions updated, or alternatively let's switch to building from source and adding to homebrew repo.

**Comment by sttz** [comment]
Hey, thanks!

I set up a formula for a source build and it was trickier than I thought. I'm doing the builds using CoreRT and .Net Core but the .Net Core SDK is only available as a Cask on Homebrew. So I wanted to use mono but mono can only build .Net Core if the .Net Core SDK is installed (took me a while to figure out, I only got TypeLoadExceptions). So I updated the project to run on .Net Framework as well, so mono can build and run it without any additional dependencies.

For now I just added the formula to the project:
https://github.com/sttz/install-unity/blob/next/install-unity.rb

You can install it using:
`brew install https://raw.githubusercontent.com/sttz/install-unity/next/install-unity.rb`

Though I think this way Homebrew won't update it, you'll have to reinstall when it gets updated. I didn't want to open another repository just for the tap, you can technically tap this repository but that will get you an extra copy of the source:
`brew tap sttz/install-unity https://github.com/sttz/install-unity.git`

`brew audit` tells me the Github project is not notable enough, so I don't know what the chances would be for submitting it to homebrew-core.

**Comment by capyvara** [comment]
Thanks, I'll try the formula later.

I think keeping a homebrew-install-unity tap repo should be easy to maintain, mine isn't even cloned, I edit it directly in github. Or for sake of easier maintenance, maybe can you can add the tap as a git submodule into this source folder?

I don't think it's worthwhile to send to homebrew core right now, it's quite useful the way it is right now.

**Comment by sttz** [comment]
I moved the formula [to a tap](https://github.com/sttz/homebrew-tap) and also added a cask for the binary.

This way, it's possible to do just:

```sh
brew cask install sttz/tap/install-unity
```

or

```sh
brew install sttz/tap/install-unity
```

to install!
