### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by TCROC** [sttz/install-unity#27]
I'm currently working on adding Windows support.  Progress can be tracked on my fork and branch here: https://github.com/TCROC/install-unity/tree/windows-support.  I'll create a pr when it's ready.

**Comment by sttz** [comment]
Cool, let know if you have questions or need some changes.

Someone tried to add Windows support earlier this year but work seems to have stopped:
https://github.com/minorai/install-unity/tree/Feature/PartialWindowsSupport

**Comment by TCROC** [comment]
@sttz Development on this is going to be slowing down now for us as well.  We found that Unity Hub cli can install Unity.  We might come back to this though if Unity Hub starts having problems.  I'm going to close this for now, but will open if back up if we get back to working on it.
