### ISSUE TITLE
[Feature Request] ensure the unity installation path matches the version exactly

### ISSUE THREAD

**Issue by taurawaxeye** [sttz/install-unity#30]
I am setting up this program with a jenkins instance to ensure unity is automatically installed before progressing with a build. You can find the the version of the unity project by inspecting the ProjectSettings\ProjectVersion.txt file.

In the scripts that I am setting up in the jenkins instance, I load that file, parse it through the yaml, and the fed it into the install-unity program, works like a charm.

However,

The next step in the build pipeline is to run that exact unity version. The install location doesn't match version fed in via command line exactly.

![chrome_AaMCFFIHfx](https://user-images.githubusercontent.com/61036294/158346962-1ce4c7e7-9ef3-448a-82be-3570933a5224.png)
![AnyDesk_x6XFpvWXMu](https://user-images.githubusercontent.com/61036294/158346990-917b62b6-68a8-449c-bebf-b5ee0dc20ecf.png)

This adds a complexity to the build process as it means addition string processing needs to be implemented. Is there currently a option to specify the install location, not just the components download location. If the install location can match the version exactly, it would make it easier to programmatically find the exact path,

**Comment by sttz** [comment]
You already have to options in the current version of `install-unity`:

- Use `install-unity run <project-path>`. This will check the `ProjectVersion.txt` file, find all installed versions of Unity with Spotlight and then choose the matching one to run the project with. Check the documentation for the options and how to pass arguments to Unity.

- Use `--opt "installPathMac=/Applications/Unity {major}.{minor}.{patch}{type}{build} ({hash})"` to always use a path with the full version number and hash when installing Unity.

**Comment by taurawaxeye** [comment]
I tried out `--opt "installPathMac=/Applications/Unity {major}.{minor}.{patch}{type}{build} ({hash})"` and received the following error after the program had downloaded files


```
WARN:  Progress bar disabled due to exception during rendering: System.AggregateException: One or more errors occurred. (One or more errors occurred. (ERROR:                            ))                                                                                                                                                                                        ---> System.AggregateException: One or more errors occurred. (ERROR:                                                                                                                    )                                                                                                                                                                                        
 ---> System.Exception: ERROR: 

   at sttz.InstallUnity.MacPlatform.InstallPkg(String filePath, CancellationToken cancellation)
   at sttz.InstallUnity.MacPlatform.Install(Queue queue, QueueItem item, CancellationToken cancellation)
   --- End of inner exception stack trace ---
   at sttz.InstallUnity.UnityInstaller.Process(InstallStep steps, Queue queue, Boolean skipChecks, CancellationToken cancellation)
   at sttz.InstallUnity.UnityInstaller.Process(InstallStep steps, Queue queue, Boolean skipChecks, CancellationToken cancellation)
   --- End of inner exception stack trace ---
   at sttz.InstallUnity.InstallUnityCLI.Install()
One or more errors occurred. (ERROR: 
)
ERROR: 

```

**Comment by taurawaxeye** [comment]
amendment. It might be relating to space on my server. Let me just confirm

**Comment by taurawaxeye** [comment]
can confirm that it is now working.

`--opt "installPathMac=/Applications/Unity {major}.{minor}.{patch}{type}{build} ({hash})"`

works
much appreciated.
