### ISSUE TITLE
Bump to use android sdk 32 -> 33 

### ISSUE THREAD

**Issue by kcbuilder** [sttz/install-unity#37]
## Problem

Currently automatically the package installing sdk 32 version, but latest update from google play require at least 33 
https://developer.android.com/google/play/requirements/target-sdk

## Solution 

Bump dependencies to use 33 api level by default

**Comment by sttz** [comment]
You're using version 2.12.0 of install-unity? Which version of Unity are you trying to install?

With the latest version, the Android dependencies are now coming directly from Unity and it's up to them to update them. For alpha and beta versions of Unity, it can take them some time to land all the changes and then update the packages – it's the same issue when using the Hub to install Unity.

**Comment by kcbuilder** [comment]
@sttz thanks for response, solved problem with installing required sdk with using `-accept-apiupdate` for batchmode for unity editor
