### ISSUE TITLE
Error when download package without 'unity' package 

### ISSUE THREAD

**Issue by nomadalex** [sttz/install-unity#6]
After download main 3 packages use `install-unity.py --download  --package-store . 5.6.2f1`, but before install them, I want to continue download iOS package use `install-unity.py --download -p Unity -p iOS --package-store . 5.6.2f1`, it will report error 'ERROR: Could not find a Unity version that matches "5.6.2f2"'

found in sources in line [795](https://github.com/sttz/install-unity/blob/master/install-unity.py#L795): `if operation == 'list' or len(packages) == 0 or 'unity' in packages:
`, need to add `or operation == 'download'` in it.

**Comment by sttz** [comment]
Thanks for the heads up!

Fixed in da0a4e5b and 0.0.7.
