### ISSUE TITLE
Exception when installing 2017.1.0f1

### ISSUE THREAD

**Issue by patrickkulling** [sttz/install-unity#8]
First of all, we are a big fan of your tool, but it stopped working with the new Unity version.

command:
```
install_unity.py --discover http://beta.unity3d.com/download/4d7fe18a2f34/MacEditorInstaller/Unity-2017.1.0f1.pkg --package Unity 2017.1.0f1 --package iOS --package Android --package WebGL -v
```

stacktrace:
```
Password:Traceback (most recent call last):
  File "/Users/wooga/workspace/jenkins/home/jobs/Maintenance/jobs/Update_Unity/workspace/label/master/install_unity.py", line 968, in <module>
    main()
  File "/Users/wooga/workspace/jenkins/home/jobs/Maintenance/jobs/Update_Unity/workspace/label/master/install_unity.py", line 958, in main
    install(version, path, selected)
  File "/Users/wooga/workspace/jenkins/home/jobs/Maintenance/jobs/Update_Unity/workspace/label/master/install_unity.py", line 686, in install
    filename = os.path.basename(config.get(pkg, 'url'))
NameError: global name 'config' is not defined
Install Unity Script 0.0.8
```

Any ideas?

Best,
Patrick

**Comment by sttz** [comment]
Sorry, a few things broke in the last update. 0.0.9 should have fixed them!

btw, I noticed you manually added the 2017.1 release candidate, which shouldn't be necessary. Before 0.0.9 it was a bit tricky to get install-unity to update the beta releases and selected the release candidate (you needed at least two commands e.g. `install-unity.py --list beta` and then `install-unity 2017`).

I improved the version selection in 0.0.9, so now the only thing you need to remember is that release candidates are still considered beta releases, so `install-unity.py 2017b` will now install the latest release candidate, if one is available.
